### ISSUE TITLE
Fichier tutoriel cassé

### ISSUE THREAD

**Issue by Sharlaan** [diplomatiegouvfr/hornet-js-formation#1]
Serait-il possible de mettre en ligne une version lisible de `HORNET_FORMATION-V-5.2.x.odp` ?
Merci

**Comment by wmoulin** [comment]
Bonjour, 
Je viens de tester (sur mon poste perso avec libre office en version 6.0.7.3) et je n'ai aucun problème, le fichier semble correct.

**Comment by Sharlaan** [comment]
Ok merci, j'ai compris pourquoi :
Il ne fallait pas faire "Enregistrer le lien sous ...", mais cliquer dessus puis utiliser le bouton "Download" sur la page suivante ... Mea Culpa.
